services:
  - type: web
    name: flask-essay-review
    runtime: python
    buildCommand: |
      apt-get update
      apt-get install -y \
        libpango-1.0-0 \
        libpangocairo-1.0-0 \
        libcairo2 \
        libffi-dev \
        shared-mime-info
      pip install -r requirements.txt
    startCommand: gunicorn app:app